import 'package:amine_s_application1/core/app_export.dart';import 'package:amine_s_application1/presentation/downloaded_tab_container_page/downloaded_tab_container_page.dart';import 'package:amine_s_application1/presentation/home_page/home_page.dart';import 'package:amine_s_application1/presentation/profile_page/profile_page.dart';import 'package:amine_s_application1/presentation/saved_page/saved_page.dart';import 'package:amine_s_application1/presentation/search_page/search_page.dart';import 'package:amine_s_application1/widgets/custom_bottom_bar.dart';import 'package:flutter/material.dart';
// ignore_for_file: must_be_immutable
class HomeContainerScreen extends StatelessWidget {GlobalKey<NavigatorState> navigatorKey = GlobalKey();

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(backgroundColor: ColorConstant.black900, body: Navigator(key: navigatorKey, initialRoute: AppRoutes.homePage, onGenerateRoute: (routeSetting) => PageRouteBuilder(pageBuilder: (ctx, ani, ani1) => getCurrentPage(routeSetting.name!), transitionDuration: Duration(seconds: 0))), bottomNavigationBar: CustomBottomBar(onChanged: (BottomBarEnum type) {Navigator.pushNamed(navigatorKey.currentContext!, getCurrentRoute(type));}))); } 
String getCurrentRoute(BottomBarEnum type) { switch (type) {case BottomBarEnum.Home: return AppRoutes.homePage; case BottomBarEnum.Search: return AppRoutes.searchPage; case BottomBarEnum.Saved: return AppRoutes.savedPage; case BottomBarEnum.Downloads: return AppRoutes.downloadedTabContainerPage; case BottomBarEnum.Me: return AppRoutes.profilePage; default: return "/";} } 
Widget getCurrentPage(String currentRoute) { switch (currentRoute) {case AppRoutes.homePage: return HomePage(); case AppRoutes.searchPage: return SearchPage(); case AppRoutes.savedPage: return SavedPage(); case AppRoutes.downloadedTabContainerPage: return DownloadedTabContainerPage(); case AppRoutes.profilePage: return ProfilePage(); default: return DefaultWidget();} } 
@override void onInit(BuildContext context) {  } 
 }
